version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
- package-ecosystem: "pip"
    directory: "/requirements/"
    target-branch: dev
    schedule:
      interval: "monthly"
