name: Build and deploy Docker image

on:
  push:
    branches:
      - 'main'
  release:
    types: [created]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push stable release
        if: github.event_name == 'release'
        id: docker_build_release
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: molpopgen/fwdpy11:stable
          file: deployment/docker/Dockerfile
          context: .
      -
        name: Build and push from main
        if: github.ref == 'refs/heads/main'
        id: docker_build_main
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: molpopgen/fwdpy11:latest
          file: deployment/docker/Dockerfile
          context: .
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
