name: Build and deploy Docker image

on:
  push:
    branches:
      - 'main'
  release:
    types: [created]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        if: github.event_name == 'release' || github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push stable release
        if: github.event_name == 'release'
        id: docker_build_release
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: molpopgen/fwdpy11:latest, molpopgen/fwdpy11:${{ github.event.release.tag_name }}
          file: deployment/docker/Dockerfile
          context: .
      -
        name: Build and push from main
        if: github.ref == 'refs/heads/main'
        id: docker_bfild_main
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: molpopgen/fwdpy11:latest
          file: deployment/docker/Dockerfile
          context: .
      -
        name: Build image
        if: github.event_name == 'pull_request'
        id: docker_build_pull_request
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: molpopgen/fwdpy11:stable
          file: deployment/docker/Dockerfile
          context: .
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
